### ISSUE TITLE
Unexpandable macros aren't defined `protected`

### ISSUE THREAD

**Issue by Skillmon** [alceu-frigeri/starray#2]
In `expl3` unexpandable functions should be defined `protected` to avoid errors if they end up in `e`- or `x`-expansion contexts.

You can see in `interface3.pdf` that the functions that are fully expandable have either a small filled, or a hollow star. As long as your code uses a function that doesn't have a star next to it in `interface3.pdf` you should define your function `protected` using `\cs_new_protected:Npn` or similar (there might be some exceptions to this rule if your functions are intended to be used inside of a `\halign` or `\valign` and issue `\omit` or `\noalign`, but those are very rare and shouldn't apply to the functions in your package).

As an example, your `\__starray_new:n`-internal function uses `\prop_new:c` which isn't expandable. Because of that you should define it with `\cs_new_protected:Npn` (and then you'll need to define every function that uses `\__starray_new:n` as `protected` as well).

Also it would be nice if your documentation could highlight which macros/functions are expandable and which aren't (similar to `interface3.pdf`).

**Comment by alceu-frigeri** [comment]
The 'same case' as in the first ticket: that's sure to be done (I mean, going over the code, and protecting the ones that need to be).
:) 
and it might be all of them (not all, but...).

**Comment by Skillmon** [comment]
Well, in practice they are separated things, so I figured I should report them separately... Sorry if you'd have preferred to get the two (indeed closely related) thingies as a single ticket :)

Btw. your package is a great idea otherwise (I just so happen to be really fixated on (un)expandability).

**Comment by alceu-frigeri** [comment]
no problem at all (two tickets), though the 'solution' for both is basically the same, and quite easy. I just have to go over the definitions and look over which 'has to be', 'which might have to', and if there is some that don't need to be protected.

**Comment by alceu-frigeri** [comment]
closing it now, managed to submit it to ctan (doc and all).
