### ISSUE TITLE
Remove all V type expansion. Not supported by latex3, might brake

### ISSUE THREAD

**Issue by alceu-frigeri** [alceu-frigeri/starray#6]
To be seen what can be done, but from https://github.com/latex3/latex3/issues/1466 there isn't much hope for  this package moving forward. 

To serialize/de-serialize the sub-structures (property lists and sequences) at each and every access would incur in a huge performance hit (and the package is already heavy as it is now).

**Comment by Skillmon** [comment]
Sorry if I sometimes sound too harsh, the comment over at latex3/latex3#1466 was meant to protect you from any possible breakage nothing more nothing less. I haven't used `starray` yet, neither did I look much into its documentation or implementation, but perhaps using a `tl` with groups inside it and `\tl_item:Nn` instead of `\seq_item:Nn` might be viable (if that's the only accessor to sequences you need, as I said, I don't know). Nothing much in this regard for property lists though, unless you only expect few items per stored list, in which case storing and accessing as `key=val` might be fine.

**Comment by alceu-frigeri** [comment]
no grievance (besides me with myself).
but, the structure I implemented is rather large.
better said, the main Idea is having a 'specialized structure' (a starray) which in it's simplest form is just an **array** of property lists, which can be accessed like
\starray_get_prop:nn {starray-name[index]}{prop}
whereas index might be a number, might be a hash value or omitted all together (in which case an iterator will be used).

And from there, a starray might have, as an internal structure, besides normal properties (like a property list), a nested starray.

The whole point of the package was to allow something like
\starray_get_prop:nn {starray-name[index].sub[index].sub[index]}{prop}

well, I devised it because I got tired of \expandafter nightmare when referencing a command sequence which would be constructed from many counters (and keeping score of which counter was for which sub-index... and so on...

EDIT: to give you, perhaps, some sky-high, overview: for each 'sub-starray' I keep a property list which stores the structure current iterator, the number of elements, a sequence with a pointer to all elements (each instance is stored in a separate property list) a property list being used as a hash table (index/hash values pointing to a given element/instance)...
and this 'index property list' is stored inside a main one... 
Not forgetting, yeah, each 'instance' might at it turn have one or more sub-starrays... and every sub-starray instance demands its own 'description/store structure'.

one way to circumvent it, would be to create 'randomized' auxiliary property lists, and instead of storing the property list, I would just store its 'address'... but that would implies in a quite large number of extra property lists names... (In one case I already had to increase pdflatex resource pool, so, lol)

**Comment by alceu-frigeri** [comment]
Basically done. All V-expansions of (property and sequence lists) removed. Code mostly adjusted. 
Some auxiliary property lists ( ... ```_base_prop```) now holds basically nothing but a reference to the ...```_def_prop```, so to be seen if left as it is now (overkill solution, but still a flexible one), or further change the code around it.
